[build]
  functions = "./functions" # where our functions are stored

# Rewrite url to hide ".netlify/functions"
[[redirects]]
  from = "/send"
  to = "/.netlify/functions/send"
  status = 200

[dev]
  autoLaunch = false