name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on node 16 and ubuntu-latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: format
        run: yarn format:check
